### PR TITLE
fix: Bump minimum required Selenium version to `4.4.0`

### LINKED ISSUE #1694: cannot be cast to class io.appium.java_client.android.AndroidDriver while using EventFiringDecorator
## Description

I'm trying to use the decorator mechanism provided by selenium 4.
But following the doc to decorate the android driver, I get the exception

java.lang.ClassCastException: class jdk.proxy2.$Proxy22 cannot be cast to class io.appium.java_client.android.AndroidDriver (jdk.proxy2.$Proxy22 is in module jdk.proxy2 of loader 'app'; io.appium.java_client.android.AndroidDriver is in unnamed module of loader 'app')

## Environment

Java client build version or git revision if you use some snapshot: 8.0.0
Appium server version or git revision if you use some snapshot: 1.22.3
Desktop OS/version used to run Appium if necessary: Mac Monterey
Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: Appium.exe
Mobile platform/version under test: android
Real device or emulator/simulator: Both

## Details

Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]

 AndroidDriver driver = new AndroidDriver(url, driverCapabilities);
 driver=(AndroidDriver) new EventFiringDecorator(new MyLIstner()).decorate(driver);

SImilar to Cannot decorate AndroidDriver (probably the same for IOSDriver #1643

### PR DESCRIPTION
**Pull request by valfirst**
## Change list

Fixes #1694
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] No changes in production code.
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

Selenium `4.4.0` contains fixes for #1694

### CODE REVIEW

File: src/main/java/io/appium/java_client/remote/AppiumW3CHttpCommandCodec.java [hunk 1]
```diff
@@ -51,7 +42,6 @@ public AppiumW3CHttpCommandCodec() {
         defineCommand(GET_ELEMENT_ATTRIBUTE, get("/session/:sessionId/element/:id/attribute/:name"));
         defineCommand(IS_ELEMENT_DISPLAYED, get("/session/:sessionId/element/:id/displayed"));
         defineCommand(GET_PAGE_SOURCE, get("/session/:sessionId/source"));
-        defineCommand(SEND_KEYS_TO_ACTIVE_ELEMENT, post("/session/:sessionId/actions"));
```
Comment (valfirst) [inline src/main/java/io/appium/java_client/remote/AppiumW3CHttpCommandCodec.java:54]: `org.openqa.selenium.remote.DriverCommand.SEND_KEYS_TO_ACTIVE_ELEMENT` is removed in https://github.com/SeleniumHQ/selenium/commit/4dcc9c44f1afcf6cdd1b7d76dc9115358b29c2ea

**Review by SrinivasanTarget — APPROVED** [review]

**Review by asolntsev — APPROVED** [review]
